spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DocumentAutomation
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true
jwt:
  secret: ENC(pnblg3uyjOXNjmbShqjPOrDJkgxc57a0JMualct6qS6iOicZb9lFFanvbsepMBLqwebeA6lAZtKZXp1DrJ0ZtcdZcOZSvBvZ)
  expiration: 86400000  # 24시간 (밀리초 단위)

#jasypt:
#  encryptor:
#    bean: jasyptEncryptor
#    password: ${ENCRYPT_KEY}


logging:
  level:
    org.hibernate.SQL: debug