spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DocumentAutomation;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true
jwt:
  secret: yourVeryLongAndSecureSecretKeyHerePleaseMakeItLongEnough
  expiration: 86400000  # 24시간 (밀리초 단위)

logging:
  level:
    org.hibernate.SQL: debug